# Generated by Django 5.2.16 on 2026-07-28 12:17

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=40)),
                ('site', models.CharField(blank=True, max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('retired', 'Retired')], default='published', max_length=20)),
                ('default_size', models.CharField(default='1:1', max_length=20)),
                ('default_resolution', models.CharField(default='1k', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RuleProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=40)),
                ('site', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('version', models.CharField(default='v1', max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('retired', 'Retired')], default='draft', max_length=20)),
                ('source_url', models.URLField(blank=True)),
                ('checked_at', models.DateField(blank=True, null=True)),
                ('rules', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('operator', 'Operator'), ('admin', 'Admin')], default='operator', max_length=20)),
                ('daily_generation_limit', models.PositiveIntegerField(default=100)),
                ('must_change_password', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=80)),
                ('object_type', models.CharField(max_length=80)),
                ('object_id', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('platform', models.CharField(default='shopee', max_length=40)),
                ('site', models.CharField(default='SG', max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('uploading', 'Uploading'), ('organizing', 'Organizing'), ('ready', 'Ready'), ('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('partial', 'Partial'), ('needs_input', 'Needs input'), ('failed', 'Failed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('global_prompt', models.TextField(blank=True)),
                ('confirmed_generation_key', models.UUIDField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('txt', 'Text')], max_length=10)),
                ('original_filename', models.CharField(max_length=255)),
                ('storage_path', models.CharField(max_length=500)),
                ('sha256', models.CharField(max_length=64)),
                ('file_size', models.PositiveIntegerField()),
                ('content_type', models.CharField(max_length=100)),
                ('validation_status', models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('invalid', 'Invalid')], default='valid', max_length=20)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('text_content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='platform_app.batch')),
            ],
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('product_name', models.CharField(blank=True, max_length=200)),
                ('product_facts', models.TextField(blank=True)),
                ('identity_lock', models.TextField(blank=True)),
                ('prompt_override', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='platform_app.batch')),
            ],
        ),
        migrations.CreateModel(
            name='ClusterAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('primary', 'Primary'), ('reference', 'Reference')], max_length=20)),
                ('order', models.PositiveIntegerField(default=1)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_asset', to='platform_app.asset')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_assets', to='platform_app.cluster')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='cluster',
            name='assets',
            field=models.ManyToManyField(related_name='clusters', through='platform_app.ClusterAsset', to='platform_app.asset'),
        ),
        migrations.CreateModel(
            name='OutputSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField()),
                ('purpose', models.TextField(blank=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='platform_app.outputtemplate')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PromptVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt_text', models.TextField()),
                ('structured_output', models.JSONField(blank=True, default=dict)),
                ('source_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_versions', to='platform_app.cluster')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('preparing', 'Preparing'), ('submitting', 'Submitting'), ('submitted', 'Submitted'), ('processing', 'Processing'), ('archiving', 'Archiving'), ('completed', 'Completed'), ('failed', 'Failed'), ('submit_unknown', 'Submit unknown'), ('canceled', 'Canceled')], default='queued', max_length=20)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('prompt_text', models.TextField(blank=True)),
                ('size', models.CharField(default='1:1', max_length=20)),
                ('resolution', models.CharField(default='1k', max_length=20)),
                ('provider_task_id', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('reference_snapshot', models.JSONField(blank=True, default=list)),
                ('failure_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='platform_app.batch')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='platform_app.cluster')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_generations', to=settings.AUTH_USER_MODEL)),
                ('output_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generations', to='platform_app.outputslot')),
                ('prompt_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generations', to='platform_app.promptversion')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ResultAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_path', models.CharField(max_length=500)),
                ('source_url', models.URLField(blank=True)),
                ('sha256', models.CharField(max_length=64)),
                ('file_size', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_assets', to='platform_app.generation')),
            ],
        ),
        migrations.AddConstraint(
            model_name='clusterasset',
            constraint=models.UniqueConstraint(fields=('cluster', 'order'), name='unique_cluster_asset_order'),
        ),
        migrations.AddConstraint(
            model_name='outputslot',
            constraint=models.UniqueConstraint(fields=('template', 'order'), name='unique_template_slot_order'),
        ),
        migrations.AddConstraint(
            model_name='generation',
            constraint=models.UniqueConstraint(fields=('cluster', 'output_slot', 'attempt'), name='unique_generation_attempt'),
        ),
        migrations.AddConstraint(
            model_name='resultasset',
            constraint=models.UniqueConstraint(fields=('storage_path',), name='unique_result_storage_path'),
        ),
    ]
