# Generated by Django 5.2.16 on 2026-07-29 04:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0003_rename_prompt_provider_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generation',
            name='review_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('changes_requested', 'Changes requested'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ReviewFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('accept', 'Accept'), ('changes_requested', 'Changes requested')], max_length=20)),
                ('issue_tags', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review_feedback', to='platform_app.generation')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_feedback', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewAnnotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('stroke', 'Stroke'), ('circle', 'Circle')], max_length=20)),
                ('points', models.JSONField(blank=True, default=list)),
                ('rect', models.JSONField(blank=True, default=list)),
                ('color', models.CharField(default='#ff0000', max_length=32)),
                ('width', models.FloatField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annotations', to='platform_app.reviewfeedback')),
            ],
        ),
    ]
