# Generated by Django 5.2.16 on 2026-07-29 05:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0004_review_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyGenerationUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('org', 'Organization'), ('user', 'User')], max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('used', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_generation_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('scope', 'org'), ('user__isnull', True)), models.Q(('scope', 'user'), ('user__isnull', False)), _connector='OR'), name='valid_daily_generation_usage_scope'), models.UniqueConstraint(condition=models.Q(('scope', 'org')), fields=('date',), name='unique_daily_org_generation_usage'), models.UniqueConstraint(condition=models.Q(('scope', 'user')), fields=('date', 'user'), name='unique_daily_user_generation_usage')],
            },
        ),
    ]
