# Generated by Django 5.2.16 on 2026-07-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_app", "0005_daily_generation_usage"),
    ]

    operations = [
        migrations.AddField(
            model_name="ruleprofile",
            name="seed_key",
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="outputtemplate",
            name="seed_key",
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
