# Generated by Django 5.2.16 on 2026-07-29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform_app", "0006_ruleprofile_seed_key_outputtemplate_seed_key"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="outputslot",
            constraint=models.CheckConstraint(
                condition=models.Q(("order__gte", 1)),
                name="output_slot_order_gte_one",
            ),
        ),
    ]
