# Generated by Django 5.2.16 on 2026-07-29 11:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0007_outputslot_output_slot_order_gte_one'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkuImportItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=120)),
                ('product_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('imported', 'Imported'), ('failed', 'Failed')], max_length=20)),
                ('error_message', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='cluster',
            name='sku',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddConstraint(
            model_name='cluster',
            constraint=models.UniqueConstraint(fields=('batch', 'sku'), name='unique_batch_sku'),
        ),
        migrations.AddField(
            model_name='skuimportitem',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku_import_items', to='platform_app.batch'),
        ),
        migrations.AddField(
            model_name='skuimportitem',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sku_import_items', to='platform_app.cluster'),
        ),
    ]
