# Generated by Django 5.2.16 on 2026-07-30 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0009_sku_import_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='last_import_mode',
            field=models.CharField(choices=[('auto', 'Auto'), ('organize', 'Organize')], default='organize', max_length=20),
        ),
        migrations.AddField(
            model_name='cluster',
            name='analysis_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cluster',
            name='auto_generate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cluster',
            name='preparation_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cluster',
            name='preparation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('blocked', 'Blocked'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='cluster',
            name='relation_type',
            field=models.CharField(choices=[('single_product', 'Single product'), ('variant_group', 'Variant group')], default='single_product', max_length=40),
        ),
        migrations.AddField(
            model_name='promptversion',
            name='output_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prompt_versions', to='platform_app.outputslot'),
        ),
    ]
