# Generated by Django 5.2.16 on 2026-08-04 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0015_explicit_preparation_contract'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cluster',
            index=models.Index(fields=['preparation_status', 'updated_at', 'created_at'], name='cluster_prep_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='generation',
            index=models.Index(fields=['status', 'created_at', 'id'], name='generation_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='generation',
            index=models.Index(fields=['status', 'submitted_at', 'created_at'], name='generation_poll_idx'),
        ),
    ]
